name: Test binary-install

on: [pull_request]

env:
  EXAMPLE_DIR: ./examples/rust/npm
  E2E_DIR: ./examples/rust/tests/e2e

jobs:
  binary-install:
    name: Test binary-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install binary-install
        run: npm install

      - name: Install binary-install-example
        working-directory: ${{ env.EXAMPLE_DIR}}
        run: npm install

      - name: Run tests
        working-directory: ${{ env.E2E_DIR }}
        run: npm test